### ISSUE TITLE
Change Slack Channels to Env Variables

### ISSUE THREAD

**Issue by michaelsaul** [rgardler/acs-logging-test#15]
I think it would be a little easier to change Slack channels by migrating from hard coded values in notify.py to the environment variables. I can submit a pull, but I'd welcome any other feedback first.

**Comment by rgardler** [comment]
This is already implemented: https://github.com/rgardler/acs-logging-test/blob/master/src/config.py#L7

A patch to documentation would be very welcome :-)

**Comment by michaelsaul** [comment]
Ahh, yes, I was talking about the actual channels (like #general, #info, #error)

https://github.com/michaelsaul/acs-logging-test/blob/slack-channels-env/src/notify.py

It's done, but I would love to help with the documentation too.

**Comment by rgardler** [comment]
Closed by #16 - thanks @michaelsaul
